stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:dind
  only:
    - master

  variables:
    IMAGE_NAME: $CI_PROJECT_TITLE
    TAG_LATEST: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:latest
    TAG_COMMIT: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA

  before_script:
    - apk add --no-cache python3 py3-pip
    - pip install --root-user-action=ignore --no-cache-dir awscli

  script:
    - echo "FAZENDO LOGIN NA AWS"

    - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    # Caso prefira fazer deploy no ECR para cada versão descomente o comando abaixo...
    #- docker push "$TAG_COMMIT"
    #- docker build -t "$TAG_COMMIT" .

    - docker build -t "$TAG_LATEST" .
    - docker push "$TAG_LATEST"

deploy:
  needs: [build]
  stage: deploy
  only:
    - master

  before_script:
    - apk add --no-cache openssh bash curl

  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa

    - ssh -o StrictHostKeyChecking=no -i id_rsa $EC2_USER@$EC2_HOST "
      sudo apt update -y &&
      sudo apt install -y awscli
      "
      
    - ssh -o StrictHostKeyChecking=no -i id_rsa $EC2_USER@$EC2_HOST "
      aws ecr get-login-password --region ${AWS_DEFAULT_REGION} |
      docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      "
      
    # Envia múltiplos arquivos necessários para o deploy
    - scp -o StrictHostKeyChecking=no -i id_rsa docker-compose.yaml Dockerfile $EC2_USER@$EC2_HOST:~/

    - ssh -o StrictHostKeyChecking=no -i id_rsa $EC2_USER@$EC2_HOST "
      docker compose pull &&
      docker stop ${IMAGE_NAME} || true &&
      docker container rm ${IMAGE_NAME} || true &&
      docker compose up -d --build --force-recreate --no-deps
      "

